# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

Base:
  sector:
    relocation: []
  import:
    carriers:
    - shipping-ftfuel
    - shipping-meoh

  solving:
    constraints:
      transport_fuels_only: true
      limits_volume_max:
        h2_import:
          DE:
            2050: 0

EH:
  sector:
    relocation: []
  import:
    carriers:
    - shipping-ftfuel
    - shipping-meoh

  solving:
    constraints:
      transport_fuels_only: true

WH:
  sector:
    relocation: []
  import:
    carriers:
    - pipeline-h2
    - shipping-lh2
    - shipping-ftfuel
    - shipping-meoh

  solving:
    constraints:
      transport_fuels_only: true

EHP:
  sector:
    relocation:
    - methanol
    - ammonia
    - hbi
  import:
    carriers:
    - shipping-ftfuel
    - shipping-meoh

  solving:
    constraints:
      transport_fuels_only: true

WHP:
  sector:
    relocation:
      - hbi
      - ammonia
      - methanol
      - HVC
  solving:
    constraints:
      transport_fuels_only: false